In [46]:
%load_ext autoreload
%autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [47]:
import argparse
import torch
import torch.nn.functional as F
from torch.optim import Adam
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from torch_geometric.loader import DataLoader
import os,random
import os.path as osp
import sys
import time
from utils import *

from mace.mace_gnn import MBPGNN

In [64]:
from NeuroGraph.datasets import NeuroGraphDataset

In [65]:
root = "/n/fs/scratch/rb4785/NeuroGraph_data/"
dataset = NeuroGraphDataset(root=root, name="HCPAge")

Processing...
Done!


In [66]:
d = dataset[0]

In [68]:
d.vectors

tensor([0.])

In [31]:
torch.zeros((1))

tensor([0.])

In [69]:
l = torch.nn.Linear(8, 16)

In [94]:
d.x.to('cpu')

tensor([[ 0.0000,  0.5451,  0.5538,  ...,  0.1681,  0.0870,  0.1291],
        [ 0.5451,  0.0000,  0.6339,  ...,  0.0127, -0.0067,  0.0350],
        [ 0.5538,  0.6339,  0.0000,  ...,  0.1448,  0.1179,  0.1731],
        ...,
        [ 0.1681,  0.0127,  0.1448,  ...,  0.0000,  0.3854,  0.3324],
        [ 0.0870, -0.0067,  0.1179,  ...,  0.3854,  0.0000,  0.6345],
        [ 0.1291,  0.0350,  0.1731,  ...,  0.3324,  0.6345,  0.0000]])

In [87]:
l(x).tanh()

tensor([[ 0.6720,  0.7679,  0.6730,  0.5543,  0.2376,  0.3331,  0.1627, -0.6665,
         -0.3972,  0.2057,  0.9348, -0.6944,  0.1965, -0.3750,  0.1426,  0.7873]],
       grad_fn=<TanhBackward0>)

In [95]:
from e3nn import o3

In [141]:
ir = o3.Irreps("1x0e")
ir.num_irreps

1

In [157]:
[d.x.shape for d in dataset]

[torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 torch.Size([1000, 1000]),
 

In [135]:
i = o3.Irreps([(16, (0,1))])
o3.Irrep(0, 1).count(1)

NotImplementedError: 

In [159]:
y = torch.randn((7,3))

In [176]:
[x for x in [tuple(d.x.shape) for d in dataset] if x != (1000, 1000)]

[]

In [172]:
d = dataset[-1]


In [173]:
d

Data(x=[1000, 1000], edge_index=[2, 45780], y=[1], edge_attr=[1], vectors=[1])

In [114]:
irreps = "2x0e"
if irreps.strip() != "":
  for mul_ir in irreps.split('+'):
      if 'x' in mul_ir:
          mul, ir = mul_ir.split('x')
          print(mul, ir)
          print("mul = int(mul)")
          print("ir = Irrep(ir)")
      else:
          mul = 1
          print("ir = Irrep(mul_ir)")

      # assert isinstance(mul, int) and mul >= 0
      # out.append(_MulIr(mul, ir))

2 0e
mul = int(mul)
ir = Irrep(ir)
